name: Black

on: 
  push:
    paths: 
      - '**.py'
      - '**.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        sudo apt-get install libssl-dev libcurl4-openssl-dev
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        pip install black
    - name: black
      run: |
        black pypackage.py --check -l 111 -t py37
